### ISSUE TITLE
No account recovery options

### ISSUE THREAD

**Issue by SilverEzhik** [DevelopersGuild/DG-forum#4]
I forgot my password and now I'll never log back in ¯\_(ツ)_/¯

**Comment by banhathome** [comment]
Hey Dima!

I'm sorry that happened, but fortunately we're revamping the DG-Forum and DG-Website, so that means that we'll probably wipe our entire database at some point and start over.

We originally had plans to implement some form of account recovery in-case a member forgot their password, but didn't have enough time.
